### ISSUE TITLE
Upgrade from 2023-11-07-516ab774-1 to 2023-11-10-35facc83-1 causes routing issues

### ISSUE THREAD

**Issue by KsmoinO** [openwrt/netifd#18] opened 2023-11-15 15:03 UTC
Remote routed networks using Wireguard has their network addresses modified when doing the upgrade on openwrt 23.05.0

netifd 2023-11-07-516ab774-1:
```
root@OpenWrt:~# ip r s dev private_dmz
10.33.1.0/24 dev private_dmz scope link  src 10.33.1.1 
10.33.1.5 dev private_dmz scope link 
10.33.1.6 dev private_dmz scope link 
10.33.1.10 dev private_dmz scope link 
10.81.15.0/24 dev private_dmz scope link 
192.168.1.0/24 dev private_dmz scope link 
192.168.11.0/24 dev private_dmz scope link
```
netifd 2023-11-10-35facc83-1:
```
root@OpenWrt:~# ip r s dev private_dmz
0.81.15.0/24 dev private_dmz scope link 
0.168.1.0/24 dev private_dmz scope link 
0.168.11.0/24 dev private_dmz scope link 
10.33.1.0/24 dev private_dmz scope link  src 10.33.1.1 
10.33.1.5 dev private_dmz scope link 
10.33.1.6 dev private_dmz scope link 
10.33.1.10 dev private_dmz scope link 
```

**Comment by StifflersMom** [comment] 2023-11-15 17:35
May be the same as this one https://github.com/openwrt/netifd/issues/17

**Comment by jow-** [comment] 2023-11-15 20:05
Duplicate of #17

**Closed by jow-** 2023-11-15 20:05 UTC
